//! Two build-time jobs: the Windows resources (app icon, manifest), and the
//! soundtrack manifest.
//!
//! The Windows resources are deliberately NON-FATAL: embedding needs a resource
//! compiler (the Windows SDK's `rc.exe`, or `llvm-rc`), and a machine without
//! one should still be able to build -- it just gets a binary with the default
//! icon and no manifest. A failure there is a warning, never a broken build.
//!
//! The soundtrack is enumerated rather than listed: every `.mid` in `music/`
//! becomes an entry in a generated `include_bytes!` table, so adding a track is
//! dropping a file in a folder and nothing else. `rerun-if-changed` on the
//! directory means cargo notices the new file on the next build.
use std::fmt::Write as _;

fn main() {
    #[cfg(windows)]
    {
        let ico = "assets/goblin.ico";
        println!("cargo:rerun-if-changed={ico}");
        let mut res = winresource::WindowsResource::new();
        res.set_icon(ico);
        res.set_manifest(MANIFEST);
        if let Err(e) = res.compile() {
            println!("cargo:warning=goblin resources not embedded ({e})");
        }
    }
    soundtrack();
}

/// What the exe tells Windows about itself.
///
/// `longPathAware` is the reason this exists. Without it every path the process
/// opens is cut off at 260 characters, and a video library is exactly the kind
/// of tree that runs past that -- a long series name inside a long folder name
/// on a mapped drive, and the draft fails on a file the user can see in
/// Explorer. (The machine also has to have long paths enabled, which Windows 10
/// 1607 and later do by policy; declaring it here is our half of that.)
///
/// The supported-OS list comes with it rather than as an extra: an executable
/// that carries a manifest and names no Windows version is assumed to be a
/// Vista-era program, and Windows starts lying to it about the version it is
/// running on and scaling its window itself. The four GUIDs are Windows 7, 8,
/// 8.1 and 10/11, which is every Windows this ships to.
const MANIFEST: &str = r#"<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
    </windowsSettings>
  </application>
</assembly>
"#;

/// Write `$OUT_DIR/soundtrack.rs`: a `SCORES` table of (name, bytes) for every
/// `.mid` in `music/`, sorted by filename so the build is reproducible and the
/// playlist order is the one visible in the folder.
fn soundtrack() {
    println!("cargo:rerun-if-changed=music");
    let mut files: Vec<std::path::PathBuf> = std::fs::read_dir("music")
        .map(|rd| {
            rd.flatten()
                .map(|e| e.path())
                .filter(|p| {
                    p.extension()
                        .and_then(|e| e.to_str())
                        .is_some_and(|e| e.eq_ignore_ascii_case("mid"))
                })
                .collect()
        })
        .unwrap_or_default();
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs from the `music/` directory -- do not edit.\n\
         pub static SCORES: &[(&str, &[u8])] = &[\n",
    );
    for p in &files {
        // the display name is the stem, so the console can say what is playing
        let stem = p.file_stem().unwrap_or_default().to_string_lossy();
        let abs = std::fs::canonicalize(p).unwrap_or_else(|_| p.clone());
        // forward slashes: a Windows path with backslashes is escape soup
        // inside a Rust string literal
        let abs = abs.to_string_lossy().replace('\\', "/");
        let abs = abs.strip_prefix("//?/").unwrap_or(&abs);
        let _ = writeln!(out, "    ({stem:?}, include_bytes!({abs:?})),");
    }
    out.push_str("];\n");

    // `has_music` is what lets the emptiness guard in `sound.rs` be a hard
    // assertion where there IS a soundtrack, without turning a source checkout
    // that has no `music/` into a failing test run. The soundtrack is not part
    // of the source distribution; a build with tracks in the folder still gets
    // the guard that a silent playlist never ships.
    println!("cargo::rustc-check-cfg=cfg(has_music)");
    if files.is_empty() {
        println!("cargo:warning=no .mid files in music/ -- the app will run silent");
    } else {
        println!("cargo::rustc-cfg=has_music");
    }
    let dir = std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    std::fs::write(std::path::Path::new(&dir).join("soundtrack.rs"), out)
        .expect("write the soundtrack manifest");
}
