//! `cargo xtask dist` -- build the release binary and pack the distribution zip
//! into `dist/`.
//!
//!   goblinscript-<ver>-dml.zip    exe (embedded bundle) + DirectML.dll.
//!                               Runs on any DirectX 12 GPU (NVIDIA / AMD /
//!                               Intel) as-is. This is the default and only
//!                               artifact.
//!
//! `cargo xtask dist --cuda` ALSO packs the optional CUDA variant:
//!
//!   goblinscript-<ver>-cuda.zip   the same, plus the ONNX Runtime CUDA
//!                               provider DLLs. It runs everywhere the DML zip
//!                               does (it falls back to DirectML at runtime),
//!                               but the CUDA fast path only engages for NVIDIA
//!                               users who additionally install the CUDA 12
//!                               runtime + cuDNN 9 (NVIDIA's own downloads, not
//!                               ours) -- so the 90+ MB CUDA provider DLL is
//!                               dead weight for everyone else, and the variant
//!                               is opt-in rather than shipped by default.
//!
//! Both variants ship THIRD-PARTY-NOTICES.txt (generated by cargo-about) --
//! a license obligation, so a missing file stops the pack.
//!
//! Whatever sits in `bundle/` is what gets baked in; the manifest's checkpoint
//! is printed so a stale bundle is noticed before it ships.

use anyhow::{bail, Context, Result};
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;
use zip::write::SimpleFileOptions;
use zip::CompressionMethod;

fn root() -> PathBuf {
    // xtask lives at <goblinscript>/xtask
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

/// The main crate's version, straight out of its Cargo.toml `[package]`.
fn crate_version(root: &Path) -> Result<String> {
    let toml = std::fs::read_to_string(root.join("Cargo.toml"))?;
    let mut in_package = false;
    for line in toml.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            in_package = t == "[package]";
        } else if in_package {
            if let Some(v) = t.strip_prefix("version") {
                if let Some(v) = v.trim_start().strip_prefix('=') {
                    return Ok(v.trim().trim_matches('"').to_string());
                }
            }
        }
    }
    bail!("no [package] version in {}", root.join("Cargo.toml").display());
}

fn build(root: &Path, features: &str) -> Result<()> {
    println!("\ncargo build --release --features {features}");
    let ok = Command::new("cargo")
        .current_dir(root)
        .args(["build", "--release", "--features", features])
        .status()
        .context("could not run cargo")?
        .success();
    if !ok {
        bail!("build with --features {features} failed");
    }
    Ok(())
}

/// The boot screen with its version filled in.
fn banner(ver: &str) -> String {
    GOBLIN_ART.replace("%VER%", ver)
}

/// Every catalog in `languages/`, as (source, archive name). Enumerated rather
/// than listed, like the soundtrack: adding a language is dropping a file in a
/// folder, for us exactly as much as for the person translating one.
fn languages(root: &Path) -> Result<Vec<(PathBuf, String)>> {
    let dir = root.join("languages");
    let mut out: Vec<(PathBuf, String)> = std::fs::read_dir(&dir)
        .with_context(|| format!("{} is missing", dir.display()))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("json"))
        .map(|p| {
            let name = format!("languages/{}", p.file_name().unwrap_or_default().to_string_lossy());
            (p, name)
        })
        .collect();
    out.sort_by(|a, b| a.1.cmp(&b.1));
    if !out.iter().any(|(_, n)| n == "languages/en-US.json") {
        bail!("languages/en-US.json is missing -- it is the template every translation starts from");
    }
    Ok(out)
}

fn pack(out: &Path, files: &[(PathBuf, String)], readme: &str) -> Result<()> {
    let mut z = zip::ZipWriter::new(
        File::create(out).with_context(|| format!("create {}", out.display()))?,
    );
    let opts = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    z.start_file("README.txt", opts)?;
    z.write_all(readme.as_bytes())?;
    for (src, name) in files {
        z.start_file(name.as_str(), opts)?;
        let mut f = File::open(src)
            .with_context(|| format!("{} missing -- did the build run?", src.display()))?;
        std::io::copy(&mut f, &mut z)?;
    }
    z.finish()?;
    let mb = std::fs::metadata(out)?.len() as f64 / 1e6;
    println!("  -> {} ({mb:.0} MB)", out.display());
    Ok(())
}

/// The manual, in the voice of the machine it ships with: a 1987 Goblin
/// Industries operator's guide. The section rules reuse the POST report's
/// bracket chip, so the page reads as a continuation of the boot screen above
/// it rather than as documentation bolted underneath.
///
/// The theming is a coat of paint on FACTS, never a substitute for them: every
/// requirement, flag and safety note here has to survive the voice. A raw
/// string, so Windows paths keep their backslashes -- hash-delimited because the
/// command-line examples quote their URLs, the way a shell needs them quoted.
const README_COMMON: &str = r#"
  Thank you for choosing GOBLIN INDUSTRIES. Inside this package you will
  find one (1) crew of goblins, trained to watch a video and scrawl a
  matching script: strokes where the action is, timed to the motion on
  screen. The result lands beside your video as video.funscript, ready for
  any player that reads them.

  Treat it as a solid first draft. The goblins are paid to nail the rhythm
  and the timing; anything else is yours to fine-tune in your favourite
  editor.


[ PUTTING THEM TO WORK ]------------------------------------------------

  Double-click goblinscript.exe. A picker opens in the terminal: browse
  with the arrow keys, select with Space or Enter, press S to set them
  going. In a crowded folder, / filters by name and A grabs every video at
  once, and each folder shows how many of its videos already have a script.
  The picker reopens wherever you left it, even across launches.

  Space on a FOLDER takes every video sitting in it, so a fresh drop of
  clips goes in without stepping inside. Just that one folder: videos in
  the folders below it are left alone, and you pick those by going in.

  Got a link instead of a file? Press L, paste it, and the goblins fetch it
  into the folder you are looking at and then draft it like anything else.
  That one needs yt-dlp (see WHAT THE GOBLINS NEED) -- without it there is
  no L on the keys line and nothing else changes.

  Ctrl-C stops. Whatever the goblins had finished is kept, so running that
  video again resumes instead of starting over.

  The goblins put a record on while they work. T cycles the colour scheme,
  M the sound (music, then blips only, then silence), and while the music
  is playing V sets the volume and N skips a track -- all of it remembered
  for next time, and all of it working mid-draft. A long job should not
  have to wait for the volume.


[ SPEAKING YOUR LANGUAGE ]----------------------------------------------

  The goblins speak whatever your machine speaks, if a phrasebook for it
  sits in the languages folder beside the exe. English and Chinese ship
  with them; G in the picker moves between the ones you have, and the
  choice is remembered. --lang zh-CN picks one from a command line.

  Not there yours? Copy languages/en-US.json, name it for your language
  (languages/de-DE.json, say), and translate the right-hand side of every
  line -- leave the left-hand names and anything in {braces} alone. Save
  it and start the app: your language is on the G key. Nothing to build,
  and a line you have not got to yet simply comes out in English.


[ THE REVIEW BENCH ]----------------------------------------------------

  When the drafting is done, your browser opens on the review page: the
  video plays with the scripted motion overlaid, and turning a knob (style,
  dwell confidence, stillness, depth uniformity, intensity, or a gap filler
  that scrawls a rhythm through the passages with no motion in them)
  rewrites the script in milliseconds. Press Done when it looks right.

  The strip under the video is a speed heatmap of the script. Left and
  right arrows step a frame at a time, up and down jump reversal to
  reversal, space plays and pauses. Fine tuning opens the raw number behind
  each preset, right beside the preset it overrides. Review several videos
  at once and each keeps its own style.

  Nothing leaves the machine. The page is served to your own browser and
  to nothing else.


[ VR VIDEOS ]-----------------------------------------------------------

  A goblin cannot read a VR video the way it comes -- the picture is a
  warped 360-degree bubble, and a goblin has only ever watched ordinary
  flat footage. So it asks you where to look, once.

  Hand it a VR video and it says so, then opens a page showing one flat
  view cut out of the bubble. Drag the picture to aim it, the way you would
  turn your head in a headset, until the action sits in frame. That is the
  whole job.

  The filmstrip underneath is that same aim at ten moments across the
  video: every cell should still hold the action, which is how you know one
  aim covers the lot. B loops about two seconds of real motion, and you can
  keep aiming while it runs. I and O mark a start and an end if you only
  want a stretch of a long video -- the funscript is still timed to the
  full-length original either way.

  Press Done and the goblins get to work. Several VR videos in one batch
  are aimed in the same sitting, so the drafting afterwards runs
  unattended. Your aim is remembered and never asked for twice. If a video
  is flagged as VR by mistake, press K and it is drafted as ordinary
  footage. If one is NOT spotted -- it plays as a warped bubble in your
  player but the goblins called it flat -- press B on it in the picker and
  it gets the aiming page anyway.


[ FROM A COMMAND LINE ]-------------------------------------------------

  goblinscript video.mp4                  the script lands by the video
  goblinscript a.mp4 b.mp4 c.mp4          several, one after another
  goblinscript D:\clips                   every video in that folder
  goblinscript video.mp4 --out D:\scripts put the scripts elsewhere
  goblinscript video.mp4 --review         review in the browser after
  goblinscript video.mp4 --no-vr          never stop to ask about VR
  goblinscript video.mp4 --dwells cautious --intensity 1.2
  goblinscript "https://..."              fetch the link, then draft it
  goblinscript "https://..." -- --cookies-from-browser firefox

  A fetched video lands in the folder you ran from, beside the script the
  goblins write for it; --dl-dir puts it somewhere else. Everything after a
  bare -- is handed to yt-dlp untouched, so its own options are all still
  yours.

  Style can be set directly (see --help); the review page prints the flags
  that reproduce whatever you settled on. Your own player works alongside
  it too -- the file on disk is always current.


[ HOUSE RULES ]---------------------------------------------------------

  Your existing scripts are safe. A video that already has a .funscript
  beside it is skipped, and says so, and is never overwritten -- press F in
  the picker (or pass --force) if you DO want it replaced.

  The video file itself is never modified. Nothing is uploaded, and no
  internet connection is needed at any point.


[ WHAT THE GOBLINS NEED ]-----------------------------------------------

  Windows ................... 10 (64-bit) or 11
  A graphics card ........... DirectX 12: NVIDIA, AMD or Intel
  Video memory (VRAM) ....... 8 GB
  System memory ............. 8 GB or more
  ffmpeg, on PATH ........... winget install --id Gyan.FFmpeg
                             (then open a NEW terminal -- an already-open
                             one cannot see the PATH change)
  yt-dlp, for links ......... winget install --id yt-dlp.yt-dlp
                             (optional, and only for pasting links: without
                             it the goblins never offer to fetch one)
  The DLLs from this zip .... kept in the folder with goblinscript.exe

  Reckon on roughly half the video's running time per draft. The graphics
  card is genuinely required, not merely recommended: the goblins think in
  a form only a GPU can hold, so there is no processor-only mode -- a
  machine without a supported card cannot draft at all.


[ THE SCRATCH FOLDER ]--------------------------------------------------

  While they work, the goblins keep their scratch files in cache/ next to
  the exe, and clear a video's away once its script is written. A draft
  that crashed or was interrupted keeps them, which is what lets it resume.

  --cache DIR moves the folder elsewhere. --keep-cache keeps it even after
  success, so a later re-draft of the same video skips the heavy work.
  Deleting it by hand is always safe -- the next run simply redoes the
  work.


  goblinscript --help lists every option.
"#;

const README_CUDA: &str = r"
[ THIS IS THE CUDA BUILD ]----------------------------------------------

  With the NVIDIA CUDA 12 runtime and cuDNN 9 on PATH (or their DLLs beside
  the exe), the goblins think on the CUDA provider and think faster.
  Without them they say so once and carry on with DirectML, exactly like
  the standard build. Both runtimes are NVIDIA's own downloads and are not
  included in this package.
";

/// The README's crown: the app's own boot screen, because that IS the brand.
/// Everything else GoblinScript wears is a 1987 machine warming up -- the POST
/// report in `bios.rs`, the phosphor palettes, the mascot beside the copyright
/// block -- so the zip opens on the same screen, down to the `bios.rs` column
/// arithmetic (labels dotted out to 34, values padded to 26, the real status
/// chips). The joke is entirely in the readings.
///
/// A raw string so every backslash of the mascot survives unescaped. Keep it
/// pure ASCII and no wider than the 72 columns below: this file is read in
/// Notepad more often than anywhere else, and a wrapped boot screen is a
/// broken one.
///
/// `%VER%` is filled by `banner()` from the crate version, the same way
/// `bios.rs` reads `CARGO_PKG_VERSION` -- a boot screen advertising a version
/// the binary is not would be the one lie on the page.
const GOBLIN_ART: &str = r"
             #####   #####  ######  ##      ######  ##   ##
            ##      ##   ## ##   ## ##        ##    ###  ##
            ##  ### ##   ## ######  ##        ##    ## # ##
            ##   ## ##   ## ##   ## ##        ##    ##  ###
             #####   #####  ######  ####### ######  ##   ##

             #####   #####  ######  ######  ######  #######
            ##      ##   ## ##   ##   ##    ##   ##    ##
             #####  ##      ######    ##    ######     ##
                 ## ##   ## ##  ##    ##    ##         ##
            ######   #####  ##   ## ######  ##         ##

                m a d e   b y   r e a l   g o b l i n s

   /\,/\      GOBLIN INDUSTRIES (R) SCRIPT BIOS v%VER%
  \(o.o)/     Copyright (C) 1987-2026, Goblin Industries Ltd.
   |___|      All goblins reserved.
    / \
  --------------------------------------------------------------------
  Memory test ....................... 640 KB (that's plenty)     [ OK ]
  Goblin crew ....................... 6 on duty                  [ OK ]
  Cocoa reserves .................... 2 mugs, still warm         [ OK ]
  Crayons ........................... sharpened                  [ OK ]
  Record on the deck ................ side B                     [ OK ]
  Scratch store ..................... 1 draft held               [ OK ]
  Naps taken ........................ 1 (brief)                  [WARN]
  Accelerator chain ................. the good graphics card     [ OK ]
  Scripts scrawled .................. more than anyone asked for [ OK ]
  Goblin runtime .................... loaded                     [READY]
  --------------------------------------------------------------------

     Starting GoblinScript ... _
";

fn main() -> Result<()> {
    // usage: cargo xtask dist [--cuda]
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.first().map(String::as_str) != Some("dist") {
        bail!("usage: cargo xtask dist [--cuda]");
    }
    let mut want_cuda = false;
    for a in &args[1..] {
        match a.as_str() {
            "--cuda" => want_cuda = true,
            other => bail!("unknown argument {other:?} -- usage: cargo xtask dist [--cuda]"),
        }
    }

    let root = root();
    let ver = crate_version(&root)?;
    let rel = root.join("target/release");
    let dist = root.join("dist");
    std::fs::create_dir_all(&dist)?;

    // Attribution for the third-party crates and model weights we ship. It is a
    // license obligation, not a nicety, so a missing file stops the pack rather
    // than shipping a zip without it. Generated by cargo-about, not hand-edited
    // (`cargo about generate` regenerates it).
    let notices = root.join("THIRD-PARTY-NOTICES.txt");
    if !notices.exists() {
        bail!(
            "THIRD-PARTY-NOTICES.txt is missing -- regenerate it before packing:\n  \
             cargo about generate --manifest-path Cargo.toml about.hbs -o THIRD-PARTY-NOTICES.txt"
        );
    }

    // what is about to be baked in -- a stale bundle should be seen, not shipped
    let man = std::fs::read_to_string(root.join("bundle/manifest.json"))
        .context("bundle/ is empty -- export a bundle from the training tree first")?;
    let field = |key: &str| {
        man.split(&format!("\"{key}\":"))
            .nth(1)
            .and_then(|s| s.split('"').nth(1))
            .unwrap_or("?")
            .to_string()
    };
    let enc_mb = std::fs::metadata(root.join("bundle/vjepa_pca.onnx"))?.len() / 1_000_000;
    println!(
        "bundle/: {} ({}, encoder graph {enc_mb} MB)",
        field("checkpoint"),
        field("enc_dtype"),
    );
    if field("enc_dtype") != "fp16" {
        bail!("bundle/ is not fp16 -- only the fp16 model ships; re-export it");
    }

    // The row clock this bundle will write every action on. `bundle.rs` pins
    // the arithmetic against a fixture and `grid_check.py` mirrors the constant
    // from the training side, but neither of them ever sees the manifest that
    // is about to be baked in -- a bundle exported on another grid would carry
    // its own row_hz in here and be packed without a word. Row 0 is the
    // midpoint of the tubelet pair (0, stride), and the clock is 1/row_hz.
    let num = |key: &str| -> Option<f64> {
        man.split(&format!("\"{key}\":"))
            .nth(1)?
            .trim_start()
            .split([',', '\n', '}'])
            .next()?
            .trim()
            .parse()
            .ok()
    };
    let (stride, fps, row_hz) = match (num("tubelet_stride"), num("grid_fps"), num("row_hz")) {
        (Some(s), Some(f), Some(r)) if f > 0.0 && r > 0.0 => (s, f, r),
        _ => bail!("bundle/manifest.json has no readable row clock \
                    (tubelet_stride / grid_fps / row_hz)"),
    };
    let row0 = 1000.0 * stride / 2.0 / fps;
    // the same 33.333 ms `bundle.rs` calls SHIPPED_ROW0_MS
    if (row0 - 33.333333).abs() >= 1e-4 || (row_hz - 30.0).abs() >= 1e-6 {
        bail!(
            "bundle/ is on a different row clock than the one the app decodes \
             against: row 0 at {row0:.6} ms, {row_hz} rows/s (the shipped grid \
             is 33.333333 ms and 30 rows/s). Every action would be written at \
             the wrong time -- re-export from a checkpoint on the shipped grid."
        );
    }
    println!("bundle/: row 0 at {row0:.3} ms, {row_hz} rows/s");

    // The language files ride BESIDE the exe rather than inside it: that is what
    // makes them editable, which is the whole point -- someone who does not read
    // English copies en-US.json, translates the right-hand sides, and the app
    // speaks their language with no build and no help from us. (English is also
    // compiled in, as the per-key fallback, so an incomplete or missing file can
    // never leave a screen blank.)
    let langs = languages(&root)?;
    println!(
        "languages/: {}",
        langs.iter().map(|(_, n)| n.as_str()).collect::<Vec<_>>().join(", ")
    );
    // GoblinScript's own MIT terms ride along with the binary: MIT asks that the
    // notice travel with every copy, and THIRD-PARTY-NOTICES.txt points at this
    // file by name for the app's own license.
    let license = root.join("LICENSE");
    if !license.exists() {
        bail!("LICENSE is missing -- the zips carry GoblinScript's own MIT terms");
    }
    let common: Vec<(PathBuf, String)> = [
        (rel.join("goblinscript.exe"), "goblinscript.exe".to_string()),
        (rel.join("DirectML.dll"), "DirectML.dll".to_string()),
        (license, "LICENSE".to_string()),
        (notices.clone(), "THIRD-PARTY-NOTICES.txt".to_string()),
    ]
    .into_iter()
    .chain(langs)
    .collect();

    build(&root, "embed")?;
    pack(
        &dist.join(format!("goblinscript-{ver}-dml.zip")),
        &common,
        &format!("{}\n{README_COMMON}", banner(&ver)),
    )?;

    // The CUDA variant runs everywhere the DML one does -- it falls back to
    // DirectML at runtime -- but carries a 90+ MB CUDA provider DLL that only
    // the minority who install the NVIDIA CUDA/cuDNN runtime ever use. So it is
    // opt-in (`cargo xtask dist --cuda`), not built by default.
    if want_cuda {
        build(&root, "embed,cuda")?;
        let mut cuda = common.clone();
        cuda.extend([
            (
                rel.join("onnxruntime_providers_cuda.dll"),
                "onnxruntime_providers_cuda.dll".to_string(),
            ),
            (
                rel.join("onnxruntime_providers_shared.dll"),
                "onnxruntime_providers_shared.dll".to_string(),
            ),
        ]);
        pack(
            &dist.join(format!("goblinscript-{ver}-cuda.zip")),
            &cuda,
            &format!("{}\n{README_COMMON}{README_CUDA}", banner(&ver)),
        )?;
    } else {
        println!("\n(CUDA variant skipped -- `cargo xtask dist --cuda` also builds it.)");
    }

    println!("\ndist/ is ready.");
    Ok(())
}
