//! `cargo xtask dist` -- build the release binary and pack the distribution zip
//! into `dist/`. The host decides which one: a Windows host packs the Windows
//! zips and a Linux host the Linux one, and the release workflow runs one of
//! each.
//!
//!   goblinscript-<ver>-windows-dml.zip
//!                               exe (embedded bundle) + DirectML.dll.
//!                               Runs on any DirectX 12 GPU (NVIDIA / AMD /
//!                               Intel) as-is. This is the default artifact
//!                               on Windows.
//!
//!   goblinscript-<ver>-linux-cuda.zip
//!                               binary (embedded bundle) + Microsoft's ONNX
//!                               Runtime + NVIDIA's own CUDA 12 and cuDNN 9.
//!                               CUDA is the floor off Windows rather than an
//!                               option, so there is one Linux zip and it
//!                               carries everything but the NVIDIA card and
//!                               its driver.
//!
//!   goblinscript-<ver>-windows-cuda.zip
//!                               `cargo xtask dist --cuda` ALSO packs this on
//!                               Windows: the same two runtimes, on an NVIDIA
//!                               card only. On an RTX 4090 it reads 60 ms
//!                               against DirectML's 72 -- one sixth off every
//!                               draft.
//!
//! A build has ONE GPU provider and no fallback to another, because the two do
//! not live in one ONNX Runtime: the DirectML zip links the runtime the `ort`
//! crate downloads, and the CUDA zips link Microsoft's, which has a CUDA EP
//! and no DirectML EP at all. Microsoft's is what reaches a Blackwell card --
//! the `ort` build's CUDA provider stops at sm_90 and carries no PTX to JIT
//! past it.
//!
//! On Windows the CUDA build is a SECOND zip rather than the only one because
//! those two runtimes weigh ~1.6 GB, which every AMD and Intel owner would
//! carry for nothing and could not use. The libraries are IN a zip rather than
//! a thing to go and install, because ONNX Runtime loads its provider library
//! in a way that does not resolve these dependencies from PATH:
//! `cudnn64_9.dll` ON PATH is reported missing, and only a copy beside the
//! binary is found.
//!
//! `CUDA_LIBS_DIR` (default `cuda-libs/`) and `ORT_LIB_LOCATION` are where the
//! two are read from -- the release workflow fills them, and a missing file
//! stops the pack by name. `ORT_LIB_LOCATION` is the variable cargo links
//! against as well, so a zip cannot carry a runtime its binary was not built
//! for.
//!
//! Every zip ships THIRD-PARTY-NOTICES.txt (generated by cargo-about) -- a
//! license obligation, so a missing file stops the pack. A CUDA zip's copy
//! carries NVIDIA's redistribution terms as well.
//!
//! Whatever sits in `bundle/` is what gets baked in; the manifest's checkpoint
//! is printed so a stale bundle is noticed before it ships.

use anyhow::{bail, Context, Result};
use std::fs::File;
use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::Command;
use zip::write::SimpleFileOptions;
use zip::CompressionMethod;

fn root() -> PathBuf {
    // xtask lives at <goblinscript>/xtask
    Path::new(env!("CARGO_MANIFEST_DIR")).parent().unwrap().to_path_buf()
}

/// The main crate's version, straight out of its Cargo.toml `[package]`.
fn crate_version(root: &Path) -> Result<String> {
    let toml = std::fs::read_to_string(root.join("Cargo.toml"))?;
    let mut in_package = false;
    for line in toml.lines() {
        let t = line.trim();
        if t.starts_with('[') {
            in_package = t == "[package]";
        } else if in_package {
            if let Some(v) = t.strip_prefix("version") {
                if let Some(v) = v.trim_start().strip_prefix('=') {
                    return Ok(v.trim().trim_matches('"').to_string());
                }
            }
        }
    }
    bail!("no [package] version in {}", root.join("Cargo.toml").display());
}

/// One cargo build, against one ONNX Runtime.
///
/// `ort` is the runtime to link: `Some` for a CUDA build, which links
/// Microsoft's own package, and `None` for the DirectML build, which links the
/// one the `ort` crate downloads. The variable is REMOVED rather than left
/// alone in the `None` case, because a shell that exported it for a CUDA build
/// would otherwise hand the DirectML build a runtime with no DirectML EP in
/// it, and that failure only shows up on a user's machine.
fn build(root: &Path, features: &str, ort: Option<&Path>) -> Result<()> {
    println!("\ncargo build --release --features {features}");
    let mut cmd = Command::new("cargo");
    cmd.current_dir(root).args(["build", "--release", "--features", features]);
    match ort {
        Some(dir) => {
            println!("  against the ONNX Runtime in {}", dir.display());
            cmd.env("ORT_LIB_LOCATION", dir).env("ORT_PREFER_DYNAMIC_LINK", "1");
        }
        None => {
            cmd.env_remove("ORT_LIB_LOCATION").env_remove("ORT_PREFER_DYNAMIC_LINK");
        }
    }
    let ok = cmd.status().context("could not run cargo")?.success();
    if !ok {
        bail!("build with --features {features} failed");
    }
    Ok(())
}

/// The boot screen with its version filled in.
fn banner(ver: &str) -> String {
    GOBLIN_ART.replace("%VER%", ver)
}

/// Every catalog in `languages/`, as (source, archive name). Enumerated rather
/// than listed, like the soundtrack: adding a language is dropping a file in a
/// folder, for us exactly as much as for the person translating one.
fn languages(root: &Path) -> Result<Vec<(PathBuf, String)>> {
    let dir = root.join("languages");
    let mut out: Vec<(PathBuf, String)> = std::fs::read_dir(&dir)
        .with_context(|| format!("{} is missing", dir.display()))?
        .flatten()
        .map(|e| e.path())
        .filter(|p| p.extension().and_then(|x| x.to_str()) == Some("json"))
        .map(|p| {
            let name = format!("languages/{}", p.file_name().unwrap_or_default().to_string_lossy());
            (p, name)
        })
        .collect();
    out.sort_by(|a, b| a.1.cmp(&b.1));
    if !out.iter().any(|(_, n)| n == "languages/en-US.json") {
        bail!("languages/en-US.json is missing -- it is the template every translation starts from");
    }
    Ok(out)
}

fn pack(out: &Path, files: &[(PathBuf, String)], readme: &str) -> Result<()> {
    let mut z = zip::ZipWriter::new(
        File::create(out).with_context(|| format!("create {}", out.display()))?,
    );
    let opts = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    z.start_file("README.txt", opts)?;
    z.write_all(readme.as_bytes())?;
    for (src, name) in files {
        // A zip carries no mode unless told, and a Linux unzip then writes
        // the binary and the library without the execute bit. `contains`
        // rather than `ends_with`, because a soname carries its major version
        // after the suffix: `libcudnn.so.9` is a library too.
        let mode = if name.ends_with(".exe") || name.contains(".so") || name == "goblinscript" {
            0o755
        } else {
            0o644
        };
        z.start_file(name.as_str(), opts.unix_permissions(mode))?;
        let mut f = File::open(src)
            .with_context(|| format!("{} missing -- did the build run?", src.display()))?;
        std::io::copy(&mut f, &mut z)?;
    }
    z.finish()?;
    let mb = std::fs::metadata(out)?.len() as f64 / 1e6;
    println!("  -> {} ({mb:.0} MB)", out.display());
    Ok(())
}

/// The manual, in the voice of the machine it ships with: a 1987 Goblin
/// Industries operator's guide. The section rules reuse the POST report's
/// bracket chip, so the page reads as a continuation of the boot screen above
/// it rather than as documentation bolted underneath.
///
/// The theming is a coat of paint on FACTS, never a substitute for them: every
/// requirement, flag and safety note here has to survive the voice. A raw
/// string, so Windows paths keep their backslashes -- hash-delimited because the
/// command-line examples quote their URLs, the way a shell needs them quoted.
const README_COMMON: &str = r#"
  Thank you for choosing GOBLIN INDUSTRIES. Inside this package you will
  find one (1) crew of goblins, trained to watch a video and scrawl a
  matching script: strokes where the action is, timed to the motion on
  screen. The result lands beside your video as video.funscript, ready for
  any player that reads them.

  Treat it as a solid first draft. The goblins are paid to nail the rhythm
  and the timing; anything else is yours to fine-tune in your favourite
  editor.


[ PUTTING THEM TO WORK ]------------------------------------------------

  %START% A picker opens in the terminal: browse
  with the arrow keys, select with Space or Enter, press S to set them
  going. In a crowded folder, / filters by name and A grabs every video at
  once, and each folder shows how many of its videos already have a script.
  The picker reopens wherever you left it, even across launches.

  Space on a FOLDER takes every video sitting in it, so a fresh drop of
  clips goes in without stepping inside. Just that one folder: videos in
  the folders below it are left alone, and you pick those by going in.

  Got a link instead of a file? Press L, paste it, and the goblins fetch it
  into the folder you are looking at and then draft it like anything else.
  That one needs yt-dlp (see WHAT THE GOBLINS NEED) -- without it there is
  no L on the keys line and nothing else changes.

  Ctrl-C stops. Whatever the goblins had finished is kept, so running that
  video again resumes instead of starting over.

  The goblins put a record on while they work. T cycles the colour scheme,
  M the sound (music, then blips only, then silence), and while the music
  is playing V sets the volume and N skips a track -- all of it remembered
  for next time, and all of it working mid-draft. A long job should not
  have to wait for the volume.


[ SPEAKING YOUR LANGUAGE ]----------------------------------------------

  The goblins speak whatever your machine speaks, if a phrasebook for it
  sits in the languages folder beside the exe. English and Chinese ship
  with them; G in the picker moves between the ones you have, and the
  choice is remembered. --lang zh-CN picks one from a command line.

  Not there yours? Copy languages/en-US.json, name it for your language
  (languages/de-DE.json, say), and translate the right-hand side of every
  line -- leave the left-hand names and anything in {braces} alone. Save
  it and start the app: your language is on the G key. Nothing to build,
  and a line you have not got to yet simply comes out in English.


[ WHAT THE GOBLINS WATCH ]----------------------------------------------

  Before they start, your browser opens on the crop page. It draws, on each
  shot of the video, the part of the picture the goblins are about to
  watch: they see only what is inside that box, which is what lets them
  read a small piece of a wide frame.

  If the box is on the action, click the green button and they go to work.
  If it is not, drag the box onto the action first, or drag a corner to
  change its size. "Use for all shots" puts one box on the whole video.
  "Let the goblins pick" puts their own box back.

  Drag the bar under the picture to move through the video, or press Space
  to play it. The left and right arrows step one frame, with Shift one
  second; the up and down arrows go from shot to shot. L plays one shot
  again and again while you move the box on it, and G shows you only what
  is inside the box -- the picture as the goblins get it.

  What you draw is kept for that video. A new version of GoblinScript, or
  new goblins, do not throw it away. K in the picker turns the page off for
  a batch that runs alone; --no-crop-edit does the same from a command
  line, and the goblins then use the box they picked.


[ THE REVIEW BENCH ]----------------------------------------------------

  When the drafting is done, your browser opens on the review page: the
  video plays with the scripted motion overlaid, and turning a knob (style,
  dwell confidence, stillness, depth uniformity, intensity, or a gap filler
  that scrawls a rhythm through the passages with no motion in them)
  rewrites the script in milliseconds. Press Done when it looks right.

  The strip under the video is a speed heatmap of the script. Left and
  right arrows step a frame at a time, up and down jump reversal to
  reversal, space plays and pauses. Fine tuning opens the raw number behind
  each preset, right beside the preset it overrides. Review several videos
  at once and each keeps its own style.

  Nothing leaves the machine. The page is served to your own browser and
  to nothing else.


[ VR VIDEOS ]-----------------------------------------------------------

  A goblin cannot read a VR video the way it comes -- the picture is a
  warped 360-degree bubble, and a goblin has only ever watched ordinary
  flat footage. So it asks you where to look, once.

  Hand it a VR video and it says so, then opens a page showing one flat
  view cut out of the bubble. Drag the picture to aim it, the way you would
  turn your head in a headset, until the action sits in frame. That is the
  whole job.

  The filmstrip underneath is that same aim at ten moments across the
  video: every cell should still hold the action, which is how you know one
  aim covers the lot. B loops about two seconds of real motion, and you can
  keep aiming while it runs. I and O mark a start and an end if you only
  want a stretch of a long video -- the funscript is still timed to the
  full-length original either way.

  Press Done and the goblins get to work. Several VR videos in one batch
  are aimed in the same sitting, so the drafting afterwards runs
  unattended. Your aim is remembered and never asked for twice. If a video
  is flagged as VR by mistake, press K and it is drafted as ordinary
  footage. If one is NOT spotted -- it plays as a warped bubble in your
  player but the goblins called it flat -- press B on it in the picker and
  it gets the aiming page anyway.


[ FROM A COMMAND LINE ]-------------------------------------------------

  goblinscript video.mp4                  the script lands by the video
  goblinscript a.mp4 b.mp4 c.mp4          several, one after another
  goblinscript D:\clips                   every video in that folder
  goblinscript video.mp4 --out D:\scripts put the scripts elsewhere
  goblinscript video.mp4 --review         review in the browser after
  goblinscript video.mp4 --no-vr          never stop to ask about VR
  goblinscript video.mp4 --dwells cautious --intensity 1.2
  goblinscript "https://..."              fetch the link, then draft it
  goblinscript "https://..." -- --cookies-from-browser firefox

  A fetched video lands in the folder you ran from, beside the script the
  goblins write for it; --dl-dir puts it somewhere else. Everything after a
  bare -- is handed to yt-dlp untouched, so its own options are all still
  yours.

  Style can be set directly (see --help); the review page prints the flags
  that reproduce whatever you settled on. Your own player works alongside
  it too -- the file on disk is always current.


[ HOUSE RULES ]---------------------------------------------------------

  Your existing scripts are safe. A video that already has a .funscript
  beside it is skipped, and says so, and is never overwritten -- press F in
  the picker (or pass --force) if you DO want it replaced.

  The video file itself is never modified. Nothing is uploaded, and no
  internet connection is needed at any point.


[ WHAT THE GOBLINS NEED ]-----------------------------------------------

%NEEDS%

  Reckon on roughly half the video's running time per draft. The graphics
  card is genuinely required, not merely recommended: the goblins think in
  a form only a GPU can hold, so there is no processor-only mode -- a
  machine without a supported card cannot draft at all.


[ THE SCRATCH FOLDER ]--------------------------------------------------

  While they work, the goblins keep their scratch files in cache/ next to
  the exe, and clear a video's away once its script is written. A draft
  that crashed or was interrupted keeps them, which is what lets it resume.

  --cache DIR moves the folder elsewhere. --keep-cache keeps it even after
  success, so a later re-draft of the same video skips the heavy work.
  Deleting it by hand is always safe -- the next run simply redoes the
  work.


  goblinscript --help lists every option.
"#;

/// The requirement table, per platform. Same rows, each platform's own
/// spelling of them: the package manager, the graphics API, the file that has
/// to stay beside the binary.
const NEEDS_WINDOWS: &str = r"  Windows ................... 10 (64-bit) or 11
  A graphics card ........... %CARD%
  Video memory (VRAM) ....... 8 GB
  System memory ............. 8 GB or more
  ffmpeg, on PATH ........... winget install --id Gyan.FFmpeg
                             (then open a NEW terminal -- an already-open
                             one cannot see the PATH change)
  yt-dlp, for links ......... winget install --id yt-dlp.yt-dlp
                             (optional, and only for pasting links: without
                             it the goblins never offer to fetch one)
  The DLLs from this zip .... kept in the folder with goblinscript.exe";

const NEEDS_LINUX: &str = r"  Linux ..................... x86-64, Ubuntu 24.04 or newer, or the like
                             (glibc 2.38: Fedora 39, Debian 13, Arch)
  A graphics card ........... NVIDIA, GTX 10 series or newer, with
                             NVIDIA's own driver, version 525 or newer
                             (CUDA is the only GPU path off Windows. The
                             CUDA and cuDNN libraries are in this package,
                             so there is nothing from NVIDIA to install
                             beyond the driver itself)
  Video memory (VRAM) ....... 8 GB
  System memory ............. 8 GB or more
  ffmpeg, on PATH ........... sudo apt install ffmpeg
                             (or your distribution's own package)
  yt-dlp, for links ......... sudo apt install yt-dlp
                             (optional, and only for pasting links: without
                             it the goblins never offer to fetch one)
  The .so from this zip ..... kept in the folder with goblinscript";

/// The operator's guide for one package: the common text with its platform
/// slots filled.
///
/// `cuda` is what the reader's card has to be, and the two Windows packages
/// differ on exactly that line: the DirectML one takes any DirectX 12 card,
/// and the CUDA one takes an NVIDIA card and stops on anything else.
fn readme(ver: &str, windows: bool, cuda: bool) -> String {
    let start = if windows {
        "Double-click goblinscript.exe."
    } else {
        "Run ./goblinscript in a terminal."
    };
    const CARD_CUDA: &str = "NVIDIA, GTX 10 series or newer, with NVIDIA's\n                             own driver, version 525 or newer";
    let needs = if windows {
        NEEDS_WINDOWS
            .replace("%CARD%", if cuda { CARD_CUDA } else { "DirectX 12: NVIDIA, AMD or Intel" })
    } else {
        NEEDS_LINUX.to_string()
    };
    format!(
        "{}\n{}",
        banner(ver),
        README_COMMON.replace("%START%", start).replace("%NEEDS%", &needs)
    )
}

/// NVIDIA's own runtime, packed beside the binary in every CUDA zip.
///
/// This is the MINIMUM that draws a correct draft, measured against the
/// runtime the CUDA packages actually carry by removing libraries until a
/// graph broke. Three of them are direct imports of the CUDA provider --
/// `cudart`, `cublas`, `cublasLt` -- and the rest are cuDNN, which the
/// provider opens by name at the first node that needs it. Dropping
/// `cudnn_engines_precompiled` fails the shot-cut detector's first
/// convolution, and dropping cuDNN entirely fails its `ReduceL2`.
///
/// What is NOT here is as measured as what is: `cudnn_adv`, `cudnn_cnn`,
/// `cufft`, `curand` and `nvrtc` all ship with CUDA and none of them is
/// reached -- 642 MB that changed no timing and broke no graph.
///
/// They are IN the zip rather than a thing to go and install because ONNX
/// Runtime loads its provider library in a way that does not resolve these
/// dependencies from PATH: `cudnn64_9.dll` ON PATH is reported missing, and
/// only a copy beside the binary is found. An installed CUDA is not enough.
///
/// The weight is real (`cublasLt` and `cudnn_engines_precompiled` are ~500 MB
/// each and neither has a smaller form), which is why the Windows CUDA build
/// is a zip of its own. On Linux there is no choice to make: the CUDA provider
/// is the only GPU path, so its libraries go in the one zip.
///
/// A Linux name is the SONAME, not the file in NVIDIA's archive: the archive
/// ships `libcudnn.so.9.10.2` with `libcudnn.so.9` pointing at it, and the
/// loader asks for the soname. The pack reads through the link, so the zip
/// holds one real file under the name the loader looks for.
const CUDA_RUNTIME_WINDOWS: &[&str] = &[
    "cudart64_12.dll",
    "cublas64_12.dll",
    "cublasLt64_12.dll",
    "cudnn64_9.dll",
    "cudnn_engines_precompiled64_9.dll",
    "cudnn_engines_runtime_compiled64_9.dll",
    "cudnn_graph64_9.dll",
    "cudnn_heuristic64_9.dll",
    "cudnn_ops64_9.dll",
];

/// The ONNX Runtime a CUDA zip carries, out of Microsoft's own package.
///
/// The DirectML zip has none of this: there the runtime is linked into the exe
/// by the `ort` crate, which downloads a build of its own. A CUDA zip cannot
/// use that build, because its CUDA provider is compiled for sm_75, sm_80 and
/// sm_90 with no PTX, which leaves out every Blackwell card. Microsoft's
/// package covers sm_61 through sm_120 on Windows and sm_60 through sm_120 on
/// Linux, so a CUDA zip links that and ships it beside the binary.
///
/// The TensorRT provider is in the same package and is NOT here: nothing asks
/// for it, and on Linux it would be another 850 KB of a file no session opens.
const ORT_RUNTIME_WINDOWS: &[&str] = &[
    "onnxruntime.dll",
    "onnxruntime_providers_cuda.dll",
    "onnxruntime_providers_shared.dll",
];

/// The same runtime under Linux's names. See [`ORT_RUNTIME_WINDOWS`].
const ORT_RUNTIME_LINUX: &[&str] = &[
    "libonnxruntime.so.1",
    "libonnxruntime_providers_cuda.so",
    "libonnxruntime_providers_shared.so",
];

/// The same runtime under Linux's names. See [`CUDA_RUNTIME_WINDOWS`].
const CUDA_RUNTIME_LINUX: &[&str] = &[
    "libcudart.so.12",
    "libcublas.so.12",
    "libcublasLt.so.12",
    "libcudnn.so.9",
    "libcudnn_engines_precompiled.so.9",
    "libcudnn_engines_runtime_compiled.so.9",
    "libcudnn_graph.so.9",
    "libcudnn_heuristic.so.9",
    "libcudnn_ops.so.9",
];

/// NVIDIA's terms travel with NVIDIA's libraries. The CUDA EULA and the cuDNN
/// SLA both allow an application to redistribute them and both ask that the
/// application say so, so a CUDA zip's notices file carries this and the dml
/// zip's does not.
const CUDA_NOTICE: &str = "

================================================================================
NVIDIA CUDA runtime and cuDNN
================================================================================

This package contains redistributable libraries of the NVIDIA CUDA Toolkit and
NVIDIA cuDNN, which are the property of NVIDIA Corporation. They are used under
the NVIDIA CUDA Toolkit End User License Agreement and the NVIDIA cuDNN
Software License Agreement, whose Attachment A and equivalent clause permit
redistribution of these libraries as part of an application.

  CUDA Toolkit EULA .... https://docs.nvidia.com/cuda/eula/index.html
  cuDNN SLA ............ https://docs.nvidia.com/deeplearning/cudnn/sla/index.html

The files are: ";

/// Where the generated notices sign off. A CUDA zip's copy has one more
/// section, and it belongs above this rather than after the last line of a
/// file that has already said it ended. `cargo about` writes it from
/// `about.hbs`, so the two move together.
const CLOSING_RULE: &str = "================================================================================
End of Third-Party Notices.";

/// The CUDA zip's extra paragraph. What the reader has to do differs between
/// the platforms -- on Windows nothing, because the libraries are in the zip;
/// on Linux they are NVIDIA's own download -- and the zip is read by someone
/// standing on one of them.
fn readme_cuda(windows: bool) -> String {
    if windows {
        "
[ THIS IS THE CUDA BUILD ]----------------------------------------------

  The goblins think on NVIDIA's CUDA provider here, which is about one
  sixth faster than the standard build. It needs an NVIDIA card and
  NVIDIA's driver, version 525 or newer, and nothing else: the CUDA 12 and
  cuDNN 9 libraries are in this package, and they are what makes it the
  larger download. Keep every file in the folder with goblinscript.exe --
  these libraries are found there and nowhere else, PATH included.

  This package is for NVIDIA cards only, and it says so and stops on any
  other card. For an AMD or Intel card, take the -windows-dml package: it
  runs on any DirectX 12 card and is a much smaller download.
"
        .to_string()
    } else {
        "
[ THIS IS THE CUDA BUILD ]----------------------------------------------

  The goblins think on NVIDIA's CUDA provider here, and off Windows that
  is the only path they have. It needs an NVIDIA card and its driver, and
  nothing else: the CUDA 12 and cuDNN 9 libraries are in this package, and
  they are what makes it a large download. Keep every file in the folder
  with goblinscript -- these libraries are found there and nowhere else.
"
        .to_string()
    }
}

/// The README's crown: the app's own boot screen, because that IS the brand.
/// Everything else GoblinScript wears is a 1987 machine warming up -- the POST
/// report in `bios.rs`, the phosphor palettes, the mascot beside the copyright
/// block -- so the zip opens on the same screen, down to the `bios.rs` column
/// arithmetic (labels dotted out to 34, values padded to 26, the real status
/// chips). The joke is entirely in the readings.
///
/// A raw string so every backslash of the mascot survives unescaped. Keep it
/// pure ASCII and no wider than the 72 columns below: this file is read in
/// Notepad more often than anywhere else, and a wrapped boot screen is a
/// broken one.
///
/// `%VER%` is filled by `banner()` from the crate version, the same way
/// `bios.rs` reads `CARGO_PKG_VERSION` -- a boot screen advertising a version
/// the binary is not would be the one lie on the page.
const GOBLIN_ART: &str = r"
             #####   #####  ######  ##      ######  ##   ##
            ##      ##   ## ##   ## ##        ##    ###  ##
            ##  ### ##   ## ######  ##        ##    ## # ##
            ##   ## ##   ## ##   ## ##        ##    ##  ###
             #####   #####  ######  ####### ######  ##   ##

             #####   #####  ######  ######  ######  #######
            ##      ##   ## ##   ##   ##    ##   ##    ##
             #####  ##      ######    ##    ######     ##
                 ## ##   ## ##  ##    ##    ##         ##
            ######   #####  ##   ## ######  ##         ##

                m a d e   b y   r e a l   g o b l i n s

   /\,/\      GOBLIN INDUSTRIES (R) SCRIPT BIOS v%VER%
  \(o.o)/     Copyright (C) 1987-2026, Goblin Industries Ltd.
   |___|      All goblins reserved.
    / \
  --------------------------------------------------------------------
  Memory test ....................... 640 KB (that's plenty)     [ OK ]
  Goblin crew ....................... 6 on duty                  [ OK ]
  Cocoa reserves .................... 2 mugs, still warm         [ OK ]
  Crayons ........................... sharpened                  [ OK ]
  Record on the deck ................ side B                     [ OK ]
  Scratch store ..................... 1 draft held               [ OK ]
  Naps taken ........................ 1 (brief)                  [WARN]
  Accelerator chain ................. the good graphics card     [ OK ]
  Scripts scrawled .................. more than anyone asked for [ OK ]
  Goblin runtime .................... loaded                     [READY]
  --------------------------------------------------------------------

     Starting GoblinScript ... _
";

fn main() -> Result<()> {
    // usage: cargo xtask dist [--cuda]
    let args: Vec<String> = std::env::args().skip(1).collect();
    // `cuda-libs` prints the library names this host's CUDA zip needs, one per
    // line. The release workflow copies exactly those out of NVIDIA's archives,
    // so the list lives HERE only and a name added below reaches the workflow
    // with no second edit.
    if args.first().map(String::as_str) == Some("cuda-libs") {
        let libs = if cfg!(windows) { CUDA_RUNTIME_WINDOWS } else { CUDA_RUNTIME_LINUX };
        for l in libs {
            println!("{l}");
        }
        return Ok(());
    }
    if args.first().map(String::as_str) != Some("dist") {
        bail!("usage: cargo xtask dist [--cuda] | cargo xtask cuda-libs");
    }
    let mut want_cuda = false;
    for a in &args[1..] {
        match a.as_str() {
            "--cuda" => want_cuda = true,
            other => bail!("unknown argument {other:?} -- usage: cargo xtask dist [--cuda]"),
        }
    }

    let root = root();
    let ver = crate_version(&root)?;
    // Where cargo put the binary: CARGO_TARGET_DIR when set, else target/.
    let rel = std::env::var_os("CARGO_TARGET_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("target"))
        .join("release");
    let dist = root.join("dist");
    std::fs::create_dir_all(&dist)?;

    // Attribution for the third-party crates and model weights we ship. It is a
    // license obligation, not a nicety, so a missing file stops the pack rather
    // than shipping a zip without it. Generated by cargo-about, not hand-edited
    // (`cargo about generate` regenerates it).
    let notices = root.join("THIRD-PARTY-NOTICES.txt");
    if !notices.exists() {
        bail!(
            "THIRD-PARTY-NOTICES.txt is missing -- regenerate it before packing:\n  \
             cargo about generate --manifest-path Cargo.toml about.hbs -o THIRD-PARTY-NOTICES.txt"
        );
    }

    // what is about to be baked in -- a stale bundle should be seen, not shipped
    let man = std::fs::read_to_string(root.join("bundle/manifest.json"))
        .context("bundle/ is empty -- export a bundle from the training tree first")?;
    let field = |key: &str| {
        man.split(&format!("\"{key}\":"))
            .nth(1)
            .and_then(|s| s.split('"').nth(1))
            .unwrap_or("?")
            .to_string()
    };
    let enc_mb = std::fs::metadata(root.join("bundle/vjepa_pca.onnx"))?.len() / 1_000_000;
    println!(
        "bundle/: {} ({}, encoder graph {enc_mb} MB)",
        field("checkpoint"),
        field("enc_dtype"),
    );
    if field("enc_dtype") != "fp16" {
        bail!("bundle/ is not fp16 -- only the fp16 model ships; re-export it");
    }

    // The row clock this bundle will write every action on. `bundle.rs` pins
    // the arithmetic against a fixture and `grid_check.py` mirrors the constant
    // from the training side, but neither of them ever sees the manifest that
    // is about to be baked in -- a bundle exported on another grid would carry
    // its own row_hz in here and be packed without a word. Row 0 is the
    // midpoint of the tubelet pair (0, stride), and the clock is 1/row_hz.
    let num = |key: &str| -> Option<f64> {
        man.split(&format!("\"{key}\":"))
            .nth(1)?
            .trim_start()
            .split([',', '\n', '}'])
            .next()?
            .trim()
            .parse()
            .ok()
    };
    let (stride, fps, row_hz) = match (num("tubelet_stride"), num("grid_fps"), num("row_hz")) {
        (Some(s), Some(f), Some(r)) if f > 0.0 && r > 0.0 => (s, f, r),
        _ => bail!("bundle/manifest.json has no readable row clock \
                    (tubelet_stride / grid_fps / row_hz)"),
    };
    let row0 = 1000.0 * stride / 2.0 / fps;
    // the same 33.333 ms `bundle.rs` calls SHIPPED_ROW0_MS
    if (row0 - 33.333333).abs() >= 1e-4 || (row_hz - 30.0).abs() >= 1e-6 {
        bail!(
            "bundle/ is on a different row clock than the one the app decodes \
             against: row 0 at {row0:.6} ms, {row_hz} rows/s (the shipped grid \
             is 33.333333 ms and 30 rows/s). Every action would be written at \
             the wrong time -- re-export from a checkpoint on the shipped grid."
        );
    }
    println!("bundle/: row 0 at {row0:.3} ms, {row_hz} rows/s");

    // The language files ride BESIDE the exe rather than inside it: that is what
    // makes them editable, which is the whole point -- someone who does not read
    // English copies en-US.json, translates the right-hand sides, and the app
    // speaks their language with no build and no help from us. (English is also
    // compiled in, as the per-key fallback, so an incomplete or missing file can
    // never leave a screen blank.)
    let langs = languages(&root)?;
    println!(
        "languages/: {}",
        langs.iter().map(|(_, n)| n.as_str()).collect::<Vec<_>>().join(", ")
    );
    // GoblinScript's own MIT terms ride along with the binary: MIT asks that the
    // notice travel with every copy, and THIRD-PARTY-NOTICES.txt points at this
    // file by name for the app's own license.
    let license = root.join("LICENSE");
    if !license.exists() {
        bail!("LICENSE is missing -- the zips carry GoblinScript's own MIT terms");
    }
    // The host picks the platform: the binary's name and the zip's suffix. The
    // DirectML zip is Windows only, and it carries the one library the `ort`
    // crate's own runtime needs beside it.
    let windows = cfg!(windows);
    let (exe, flavor): (&str, &str) = if windows {
        ("goblinscript.exe", "windows-dml")
    } else {
        ("goblinscript", "linux-cuda")
    };
    let common: Vec<(PathBuf, String)> = [
        (rel.join(exe), exe.to_string()),
        (license, "LICENSE".to_string()),
        (notices.clone(), "THIRD-PARTY-NOTICES.txt".to_string()),
    ]
    .into_iter()
    .chain(langs)
    .collect();

    // Where NVIDIA's redistributables are read from. They are not built here
    // and they are not in git: the release workflow unpacks them into this
    // folder from NVIDIA's own archives, and a developer points CUDA_LIBS_DIR
    // at a copy.
    let cuda_dir = std::env::var_os("CUDA_LIBS_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("cuda-libs"));
    // Microsoft's ONNX Runtime, which a CUDA build links and ships. Same
    // arrangement: fetched by the workflow, pointed at by ORT_LIB_LOCATION,
    // which is the variable cargo itself reads.
    let ort_dir = std::env::var_os("ORT_LIB_LOCATION")
        .map(PathBuf::from)
        .unwrap_or_else(|| root.join("ort-libs"));
    let cuda_libs = if windows { CUDA_RUNTIME_WINDOWS } else { CUDA_RUNTIME_LINUX };
    let ort_libs = if windows { ORT_RUNTIME_WINDOWS } else { ORT_RUNTIME_LINUX };

    // A CUDA zip is `common` with NVIDIA's terms in place of the plain notices,
    // plus NVIDIA's runtime and whatever provider libraries the platform loads
    // it through. Both platforms build one the same way; only Windows also
    // builds a zip without it.
    let cuda_payload = || -> Result<Vec<(PathBuf, String)>> {
        // Name what is missing. A zip packed without one of these builds a CUDA
        // session that dies at its first convolution on the user's machine.
        let missing: Vec<&str> =
            cuda_libs.iter().copied().filter(|l| !cuda_dir.join(l).exists()).collect();
        if !missing.is_empty() {
            bail!(
                "the CUDA zip needs NVIDIA's runtime in {} and these are not there:\n  {}\n\
                 Unpack the cuda_cudart, libcublas and cudnn archives from\n  \
                 https://developer.download.nvidia.com/compute/\n\
                 into that folder, flat, under these exact names -- or point \
                 CUDA_LIBS_DIR at a folder that holds them.",
                cuda_dir.display(),
                missing.join("\n  ")
            );
        }
        let missing: Vec<&str> =
            ort_libs.iter().copied().filter(|l| !ort_dir.join(l).exists()).collect();
        if !missing.is_empty() {
            bail!(
                "the CUDA zip ships Microsoft's ONNX Runtime, and {} does not \
                 hold:\n  {}\n\
                 Take the onnxruntime-*-gpu_cuda12 package from\n  \
                 https://github.com/microsoft/onnxruntime/releases\n\
                 and point ORT_LIB_LOCATION at its `lib` folder. That is the \
                 same variable cargo links against, so the zip can only ever \
                 carry the runtime the binary was built for.",
                ort_dir.display(),
                missing.join("\n  ")
            );
        }
        // NVIDIA's terms ride with NVIDIA's files: the generated notices, then
        // the redistribution clause and the list of what it covers. It goes in
        // BEFORE the closing rule, so the file still ends where it says it
        // ends.
        let cuda_notices = rel.join("THIRD-PARTY-NOTICES-cuda.txt");
        let generated = std::fs::read_to_string(&notices)?;
        let (body, end) = match generated.rfind(CLOSING_RULE) {
            Some(i) => (&generated[..i], &generated[i..]),
            None => (&generated[..], ""),
        };
        std::fs::write(
            &cuda_notices,
            format!(
                "{}{}{}\n\n{}",
                body.trim_end(),
                CUDA_NOTICE,
                cuda_libs.iter().map(|l| format!("\n  {l}")).collect::<String>(),
                end
            ),
        )?;
        let mut v: Vec<(PathBuf, String)> = common
            .iter()
            .filter(|(_, name)| name != "THIRD-PARTY-NOTICES.txt")
            .cloned()
            .collect();
        v.push((cuda_notices, "THIRD-PARTY-NOTICES.txt".to_string()));
        v.extend(ort_libs.iter().map(|l| (ort_dir.join(l), l.to_string())));
        v.extend(cuda_libs.iter().map(|l| (cuda_dir.join(l), l.to_string())));
        Ok(v)
    };

    if windows {
        // The DirectML zip, and the only build that links the `ort` crate's own
        // runtime: DirectML lives in that one and in no other.
        build(&root, "embed", None)?;
        pack(
            &dist.join(format!("goblinscript-{ver}-{flavor}.zip")),
            &common
                .iter()
                .cloned()
                .chain([(rel.join("DirectML.dll"), "DirectML.dll".to_string())])
                .collect::<Vec<_>>(),
            &readme(&ver, windows, false),
        )?;
    } else {
        // The Linux zip IS the CUDA build. There is no second provider off
        // Windows, so there is no second zip either.
        build(&root, "embed", Some(&ort_dir))?;
        pack(
            &dist.join(format!("goblinscript-{ver}-{flavor}.zip")),
            &cuda_payload()?,
            &format!("{}{}", readme(&ver, windows, true), readme_cuda(false)),
        )?;
    }

    // The CUDA variant is a WINDOWS thing, because that is the only platform
    // where CUDA is an alternative to something. On an RTX 4090 it reads 60 ms
    // against DirectML's 72, one sixth off every draft. It is a second zip and
    // not the only one because it carries Microsoft's ONNX Runtime and
    // NVIDIA's ~1.3 GB runtime, which no other vendor's card can use. On Linux
    // CUDA is the floor and the zip above already is that build.
    if want_cuda && windows {
        build(&root, "embed,cuda", Some(&ort_dir))?;
        pack(
            &dist.join(format!("goblinscript-{ver}-windows-cuda.zip")),
            &cuda_payload()?,
            &format!("{}{}", readme(&ver, windows, true), readme_cuda(true)),
        )?;
    } else if want_cuda {
        println!("\n(--cuda is a Windows option: the Linux zip is the CUDA build.)");
    } else {
        println!("\n(CUDA variant skipped -- `cargo xtask dist --cuda` also builds it.)");
    }

    println!("\ndist/ is ready.");
    Ok(())
}
